### ISSUE TITLE
musl.debug.py missing

### ISSUE THREAD

**Issue by mdlemay** [HexHive/datashield#1]
When I attempt to link the test program in the hello_world test directory, I encounter the following error:
```
clang-3.9: error: invalid linker name in argument '-fuse-ld=musl.debug.py'
```
I cannot find the `musl.debug.py` file anywhere in the DataShield repository.

**Comment by scottcarr** [comment]
The argument `-fuse-ld=foo` tells clang to look for `ld.foo` in your `PATH` and invoke that as the linker.  I think the root cause is I forgot to put in the documentation that `datashield/bin` should be in your `PATH`

In this case the actual file that is supposed to be the linker is `ld.musl.debug.py`

**Comment by mdlemay** [comment]
Yes, adding `datashield/bin` to my `PATH` resolved the issue.  Thanks!
